apiVersion: v1
kind: Secret
metadata:
  name: github-user-pat
  namespace: acm-policies
type: Opaque
stringData:                                   # means values are raw, and not b64 encoded
  user: githubusername                        # GitHub User
  accessToken: ghp_abcd1234efgh5678           # Personal Access Token
